### ISSUE TITLE
A template for rstudio-server?

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/devcontainer-templates#23]
PS. Might be worth thinking of a sister r2u+RStudio template, as that's come up a few times on social media since I posted my example repo.

_Originally posted by @grantmcdermott in https://github.com/rocker-org/devcontainer-templates/issues/19#issuecomment-1666694189_

**Comment by eitsupi** [comment]
I tried the following on my own computer (the existing `r2u` template with the new `rstudio-server` Feature added), but when I run `install.packages("curl")` on RStudio, the installation seems to stop at the `ading state information` step.

```json
{
	"name": "R (r2u and bspm configured)",
	"build": {
		"dockerfile": "Dockerfile"
	},
	"features": {
		"ghcr.io/rocker-org/devcontainer-features/r-apt:0": {
			"vscodeRSupport": "full",
			"installDevTools": true,
			"installRMarkdown": true,
			"installRadian": true,
			"installVscDebugger": true,
			"installBspm": true,
		},
		"ghcr.io/rocker-org/devcontainer-features/rstudio-server:0": {}
	},

	"customizations": {
		"vscode": {
			"extensions": [
				"RDebugger.r-debugger"
			],
			"settings": {
				"r.rterm.linux": "/usr/local/bin/radian",
				"r.bracketedPaste": true,
				"r.plot.useHttpgd": true
			}
		}
	},
	"postCreateCommand": {
		"rstudio-start": "rserver"
	},
	"forwardPorts": [
		8787
	]
}
```

![image](https://github.com/rocker-org/devcontainer-templates/assets/50911393/c0e1b41e-9bc3-44b9-af22-17e1f9f6e3f4)

**Comment by eitsupi** [comment]
It also does not seem to work well on Codespaces. (grantmcdermott/codespaces-r2u#5)

![image](https://github.com/rocker-org/devcontainer-templates/assets/50911393/7fbea85a-a024-4a22-b72a-e2bced02a692)

Thus, the installation stopped in the middle of the installation process.

If I run the same command in another process on VS Code, I get the following:

```r
> install.packages("curl")
Available system packages as root...
Install system packages as root...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading package lists... Done    
Building dependency tree... Done 
Reading state information... Done
Error: E:Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1776 (bspm.py), W:Be aware that removing the lock file is not a solution and may break your system., E:Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

**Comment by eddelbuettel** [comment]
What do have in Dockerfile?  In what I (and Grant) now use for 'codespace with r2u' we are just using base/jammy with your r-apt codespace feature.

**Comment by eitsupi** [comment]
> What do have in Dockerfile? In what I (and Grant) now use for 'codespace with r2u' we are just using base/jammy with your r-apt codespace feature.

This is that.
https://github.com/rocker-org/devcontainer-templates/blob/66f66c738b250ffd4d376c5dc31471afe94a9b45/src/r2u/.devcontainer/Dockerfile#L2
