### ISSUE TITLE
libXt6 missing in tidyverse:4.3 image template

### ISSUE THREAD

**Issue by kleinlennart** [rocker-org/devcontainer-templates#28]
I used the standard procedure to create a `devcontainer.json` with 
`"image": "ghcr.io/rocker-org/devcontainer/tidyverse:4.3"`

However, when I ran `quarto preview` the following error occured:

```
In grSoftVersion() :   
unable to load shared object '/usr/local/lib/R/modules//R_X11.so':   
libXt.so.6: cannot open shared object file: No such file or directory
```

I was able to fix the error by adding `sudo apt-get update -y && sudo apt-get install -y libxt6` as a `postCreateCommand`.
But I still wanted to flag this, since I saw online that others have struggled with the same issue (e.g, [https://notes.rmhogervorst.nl/post/2020/09/23/solving-libxt-so-6-cannot-open-shared-object-in-grdevices-grsoftversion/](https://notes.rmhogervorst.nl/post/2020/09/23/solving-libxt-so-6-cannot-open-shared-object-in-grdevices-grsoftversion/)).

**Comment by eitsupi** [comment]
Thank you for using this repo.
But this is expected and not a bug. See rocker-org/rocker-versioned2#731.
